### ISSUE TITLE
Request permission.

### ISSUE THREAD

**Issue by hello2mao** [decentralized-identity/uni-resolver-driver-did-ccp#1]
Hi @peacekeeper , I am the maintainer of this repo.
May I ask for a `Maintain` or `Write` permission for this repo? Our team will continue to do some work.

**Comment by peacekeeper** [comment]
Hello @hello2mao , I am sorry I probably should have informed you before moving your driver into a new repo. I just gave you `Admin` permission.

Note that if you want, you can also host your driver in any repo under your own organization, it doesn't necessarily have to be under the "decentralized-identity" organization - its Docker image can still be included as a driver in the Universal Resolver either way. However you prefer it :)

**Comment by hello2mao** [comment]
Thanks @peacekeeper  ^_^
/close
